name: Crash Report
description: One report per scenario
labels: ["crash-report"]
body:
  - type: dropdown
    id: scenario
    attributes:
      label: Scenario
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
    validations:
      required: true
  
  - type: dropdown
    id: pattern
    attributes:
      label: Crash Pattern (from the slides)
      options:
        - Null Data Pointer
        - Null Class/Struct Pointer
        - Out of Bounds - Access Violation (read)
        - Out of Bounds - Access Violation (write)
        - Null Function Pointer
        - Bad Function Pointer
        - Bad Virtual Function Call
        - Corrupt Return Address
        - Incorrect Call Stack
        - Stack Overflow
        - Division by Zero
        - Uncaught C++ Exception
    validations:
      required: true
  
  - type: input
    id: exception_code
    attributes:
      label: Exception code (e.g., 0xC0000005)
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this the pattern?
      description: Briefly justify your pattern selection (2–4 sentences).
      placeholder: "I chose Null pointer deref because …"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Root Cause Summary
      description: 2–4 sentences explaining what went wrong and why (tie to frames/instruction).
      placeholder: "Likely null pointer passed into dllX!Foo from …"
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: Call stack
      description: Copy/Paste the Call Stack from the Visual Studio Call Stack window.
      render: text
      placeholder: |
        dllX!Foo+0x30
        dllX!Bar+0x120
        app!Main+0x90
    validations:
      required: true

  - type: textarea
    id: fix
    attributes:
      label: Potential Fix / Mitigation
      description: 1–2 sentences.
      placeholder: "Add null-check in dllX!Foo; validate input in caller…"
    validations:
      required: true

  - type: checkboxes
    id: evidence
    attributes:
      label: Evidence reviewed (what did you use to trace the issue)
      options:
        - label: Registers
        - label: Stack memory
        - label: Heap memory
        - label: Disassembly
        - label: Call stack
        - label: Modules window
        - label: Live debugger (tracing)
        - label: Other (noted in Additional Context)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (optional)
      placeholder: "Anything noteworthy for partial credit."

  - type: textarea
    id: extra
    attributes:
      label: Extra Credit (optional) - Scenarios 1, 2, 6, and 7 only.  See project documentation.
      placeholder: "Anything noteworthy for extra credit."

  - type: input
    id: time
    attributes:
      label: Time Spent (hours)
      placeholder: "3.5 hours"
    validations:
      required: true
